## About Numpy

In [2]:
import numpy as np

In [10]:
arr1 = np.array([1, 2, 3, 6, 8])
print(arr1)
print(type(arr1))

print(arr1.shape)

arr1 = arr1.reshape((1, 5))
print(arr1.shape)

[1 2 3 6 8]
<class 'numpy.ndarray'>
(5,)
(1, 5)


In [15]:
arr2 = np.arange(0, 8, 2).reshape(1, 4)
print(arr2)

[[0 2 4 6]]


In [17]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
print(arr1.ndim)
print(arr2.ndim)

2
2


In [21]:
print(arr1.dtype)

int64


In [23]:
print(arr1.itemsize)
print(arr1)

8
[[1 2 3 6 8]]


In [26]:
# Numpy vectorized operations

arr1 = np.array([1, 4, 6, 8])
arr2 = np.array([3, 6, 8, 2])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[ 4 10 14 10]
[-2 -2 -2  6]
[ 3 24 48 16]
[0.33333333 0.66666667 0.75       4.        ]


In [33]:
# Some universal functions

arr = np.array([1, 2, 4, 8])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 2.         2.82842712]
[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]
[ 0.84147098  0.90929743 -0.7568025   0.98935825]
[0.         0.69314718 1.38629436 2.07944154]


In [38]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

# print(arr)

print(arr[0:2, 1:3]) # Perform slicing

[[2 3]
 [6 7]]


In [40]:
print(arr)

arr[1:] = -20

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   2   3   4]
 [-20 -20 -20 -20]
 [-20 -20 -20 -20]]


In [44]:
data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
# print(mean)

std_dev = np.std(data)
# print(std_dev)

normalized_data = (data - mean) / std_dev
print(normalized_data)

varience = np.var(data)
print(varience)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
2.0


In [52]:
# Logical operations

data = np.arange(1, 11)
print(data)

print(data[(data>5) & (data<=8)])

[ 1  2  3  4  5  6  7  8  9 10]
[6 7 8]


## About Pandas

In [2]:
import pandas as pd

In [3]:
data = [1, 2, 3, 4, 5]

# Creating series from 1-D array.
series = pd.Series(data)

print(data)
print(series)
print(type(series))

[1, 2, 3, 4, 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
# Creating series from dictionary

data = {'a': 1, 'b': 2, 'c': 3}
series = pd.Series(data)

print(series)     


a    1
b    2
c    3
dtype: int64


In [5]:
data = [29, 47, 16]
index = ['aa', 'bb', 'cc']

series = pd.Series(data, index=index)

print(series)

aa    29
bb    47
cc    16
dtype: int64


In [1]:
# About dataframe

## Creating a dataframe through dictionary
import pandas as pd

data = {
      'Name' : ['Keshav', 'Mayank', "Raju"],
      'Age' : [39, 28, 63],
      'City' : ['Kanpur', 'Lucknow', 'Goa']
}

dataframe = pd.DataFrame(data)
dataframe


Name  Age     City
0  Keshav   39   Kanpur
1  Mayank   28  Lucknow
2    Raju   63      Goa

In [2]:
## Creating a dataframe through list of dictionaries

data = [
      {'Name': 'Krish', 'Age': 32, "City": 'Banglore '},
      {'Name': 'Krish', 'Age': 32, "City": 'Banglore '},
      {'Name': 'Krish', 'Age': 32, "City": 'Banglore '},
      {'Name': 'Krish', 'Age': 32, "City": 'Banglore '}
]

df = pd.DataFrame(data)
df

Name  Age       City
0  Krish   32  Banglore 
1  Krish   32  Banglore 
2  Krish   32  Banglore 
3  Krish   32  Banglore

In [8]:
df = pd.read_csv('diabetes.csv')

# df.head(7)
df.tail(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [30]:
# How to access data from dataframe.

df = pd.DataFrame(data)
print(df)

# df['Name'] # It is actually a series (It prints entire column)

df.loc[0]

df.iloc[1][2]

    Name  Age       City
0  Krish   32  Banglore 
1  Krish   32  Banglore 
2  Krish   32  Banglore 
3  Krish   32  Banglore 


C:\Users\ASUS\AppData\Local\Temp\ipykernel_17732\3350338734.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][2]


Name  Age       City
0  Krish   32  Banglore 
1  Krish   32  Banglore 
2  Krish   32  Banglore 
3  Krish   32  Banglore

In [40]:
df

print(df.at[2, 'City'])

Banglore 


In [39]:
print(df.iat[2, 2])

Banglore 


In [50]:
df

# Performing data manipulation with dataframe.

# Adding a column
df['Salary'] = [5000, 2894, 29324, 32824]
print(df)

# Removing a column
df.drop('Salary', axis=1, inplace=True)
print(df)

    Name  Age       City  Salary
0  Krish   32  Banglore     5000
1  Krish   32  Banglore     2894
2  Krish   32  Banglore    29324
3  Krish   32  Banglore    32824
    Name  Age       City
0  Krish   32  Banglore 
1  Krish   32  Banglore 
2  Krish   32  Banglore 
3  Krish   32  Banglore 


In [114]:
# Update the value of whole column

print(df)

df['Age'] = df['Age'] + 1
print(df)

    Name  Age       City
0  Krish   94  Banglore 
1  Krish   94  Banglore 
2  Krish   94  Banglore 
3  Krish   94  Banglore 
    Name  Age       City
0  Krish   95  Banglore 
1  Krish   95  Banglore 
2  Krish   95  Banglore 
3  Krish   95  Banglore 


In [118]:
# How to drop the whole row.

# print(df)

# df.drop(1, axis=0, inplace=True)

# print(df)

print(df.describe())

        Age
count   3.0
mean   95.0
std     0.0
min    95.0
25%    95.0
50%    95.0
75%    95.0
max    95.0


## Data manipulation and analysis with pandas.

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')

# df.describe()
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [7]:
# Handling missing values

df.isnull().any(axis=0)

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [128]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [137]:
# Filling missing values with 0.

print(df.isnull().any())

df_filled = df.fillna(0)

df_filled.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool


Date        False
Category    False
Value       False
Product     False
Sales       False
Region      False
dtype: bool

In [143]:
df

df.isnull().any()

df['Value_updated'] = df['Value'].fillna(df['Value'].mean())
df

Date Category  Value   Product  Sales Region  Value_updated
0   2023-01-01        A   28.0  Product1  754.0   East      28.000000
1   2023-01-02        B   39.0  Product3  110.0  North      39.000000
2   2023-01-03        C   32.0  Product2  398.0   East      32.000000
3   2023-01-04        B    8.0  Product1  522.0   East       8.000000
4   2023-01-05        B   26.0  Product3  869.0  North      26.000000
5   2023-01-06        B   54.0  Product3  192.0   West      54.000000
6   2023-01-07        A   16.0  Product1  936.0   East      16.000000
7   2023-01-08        C   89.0  Product1  488.0   West      89.000000
8   2023-01-09        C   37.0  Product3  772.0   West      37.000000
9   2023-01-10        A   22.0  Product2  834.0   West      22.000000
10  2023-01-11        B    7.0  Product1  842.0  North       7.000000
11  2023-01-12        B   60.0  Product2    NaN   West      60.000000
12  2023-01-13        A   70.0  Product3  628.0  South      70.000000
13  2023-01-14        A   69.0  Product1  423.0   East      69.000000
14  2023-01-15        A   47.0  Product2  893.0   West      47.000000
15  2023-01-16        C    NaN  Product1  895.0  North      51.744681
16  2023-01-17        C   93.0  Product2  511.0  South      93.000000
17  2023-01-18        C    NaN  Product1  108.0   West      51.744681
18  2023-01-19        A   31.0  Product2  578.0   West      31.000000
19  2023-01-20        A   59.0  Product1  736.0   East      59.000000
20  2023-01-21        C   82.0  Product3  606.0  South      82.000000
21  2023-01-22        C   37.0  Product2  992.0  South      37.000000
22  2023-01-23        B   62.0  Product3  942.0  North      62.000000
23  2023-01-24        C   92.0  Product2  342.0   West      92.000000
24  2023-01-25        A   24.0  Product2  458.0   East      24.000000
25  2023-01-26        C   95.0  Product1  584.0   West      95.000000
26  2023-01-27        C   71.0  Product2  619.0  North      71.000000
27  2023-01-28        C   56.0  Product2  224.0  North      56.000000
28  2023-01-29        B    NaN  Product3  617.0  North      51.744681
29  2023-01-30        C   51.0  Product2  737.0  South      51.000000
30  2023-01-31        B   50.0  Product3  735.0   West      50.000000
31  2023-02-01        A   17.0  Product2  189.0   West      17.000000
32  2023-02-02        B   63.0  Product3  338.0  South      63.000000
33  2023-02-03        C   27.0  Product3    NaN   East      27.000000
34  2023-02-04        C   70.0  Product3  669.0   West      70.000000
35  2023-02-05        B   60.0  Product2    NaN   West      60.000000
36  2023-02-06        C   36.0  Product3  177.0   East      36.000000
37  2023-02-07        C    2.0  Product1    NaN  North       2.000000
38  2023-02-08        C   94.0  Product1  408.0  South      94.000000
39  2023-02-09        A   62.0  Product1  155.0   West      62.000000
40  2023-02-10        B   15.0  Product1  578.0   East      15.000000
41  2023-02-11        C   97.0  Product1  256.0   East      97.000000
42  2023-02-12        A   93.0  Product3  164.0   West      93.000000
43  2023-02-13        A   43.0  Product3  949.0   East      43.000000
44  2023-02-14        A   96.0  Product3  830.0   East      96.000000
45  2023-02-15        B   99.0  Product2  599.0   West      99.000000
46  2023-02-16        B    6.0  Product1  938.0  South       6.000000
47  2023-02-17        B   69.0  Product3  143.0   West      69.000000
48  2023-02-18        C   65.0  Product3  182.0  North      65.000000
49  2023-02-19        C   11.0  Product3  708.0  North      11.000000

In [19]:
# How to rename columns in dataframe.Age

df = df.rename(columns={'Sales': 'Sales_Data'})
df.head(10)

Date Category  Value   Product  Sales_Data Region
0  2023-01-01        A   28.0  Product1       754.0   East
1  2023-01-02        B   39.0  Product3       110.0  North
2  2023-01-03        C   32.0  Product2       398.0   East
3  2023-01-04        B    8.0  Product1       522.0   East
4  2023-01-05        B   26.0  Product3       869.0  North
5  2023-01-06        B   54.0  Product3       192.0   West
6  2023-01-07        A   16.0  Product1       936.0   East
7  2023-01-08        C   89.0  Product1       488.0   West
8  2023-01-09        C   37.0  Product3       772.0   West
9  2023-01-10        A   22.0  Product2       834.0   West

In [22]:
# How to change the datatypes in df.

df['Value_New'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df

Date Category  Value   Product  Sales_Data Region  Value_New
0   2023-01-01        A   28.0  Product1       754.0   East         28
1   2023-01-02        B   39.0  Product3       110.0  North         39
2   2023-01-03        C   32.0  Product2       398.0   East         32
3   2023-01-04        B    8.0  Product1       522.0   East          8
4   2023-01-05        B   26.0  Product3       869.0  North         26
5   2023-01-06        B   54.0  Product3       192.0   West         54
6   2023-01-07        A   16.0  Product1       936.0   East         16
7   2023-01-08        C   89.0  Product1       488.0   West         89
8   2023-01-09        C   37.0  Product3       772.0   West         37
9   2023-01-10        A   22.0  Product2       834.0   West         22
10  2023-01-11        B    7.0  Product1       842.0  North          7
11  2023-01-12        B   60.0  Product2         NaN   West         60
12  2023-01-13        A   70.0  Product3       628.0  South         70
13  2023-01-14        A   69.0  Product1       423.0   East         69
14  2023-01-15        A   47.0  Product2       893.0   West         47
15  2023-01-16        C    NaN  Product1       895.0  North         51
16  2023-01-17        C   93.0  Product2       511.0  South         93
17  2023-01-18        C    NaN  Product1       108.0   West         51
18  2023-01-19        A   31.0  Product2       578.0   West         31
19  2023-01-20        A   59.0  Product1       736.0   East         59
20  2023-01-21        C   82.0  Product3       606.0  South         82
21  2023-01-22        C   37.0  Product2       992.0  South         37
22  2023-01-23        B   62.0  Product3       942.0  North         62
23  2023-01-24        C   92.0  Product2       342.0   West         92
24  2023-01-25        A   24.0  Product2       458.0   East         24
25  2023-01-26        C   95.0  Product1       584.0   West         95
26  2023-01-27        C   71.0  Product2       619.0  North         71
27  2023-01-28        C   56.0  Product2       224.0  North         56
28  2023-01-29        B    NaN  Product3       617.0  North         51
29  2023-01-30        C   51.0  Product2       737.0  South         51
30  2023-01-31        B   50.0  Product3       735.0   West         50
31  2023-02-01        A   17.0  Product2       189.0   West         17
32  2023-02-02        B   63.0  Product3       338.0  South         63
33  2023-02-03        C   27.0  Product3         NaN   East         27
34  2023-02-04        C   70.0  Product3       669.0   West         70
35  2023-02-05        B   60.0  Product2         NaN   West         60
36  2023-02-06        C   36.0  Product3       177.0   East         36
37  2023-02-07        C    2.0  Product1         NaN  North          2
38  2023-02-08        C   94.0  Product1       408.0  South         94
39  2023-02-09        A   62.0  Product1       155.0   West         62
40  2023-02-10        B   15.0  Product1       578.0   East         15
41  2023-02-11        C   97.0  Product1       256.0   East         97
42  2023-02-12        A   93.0  Product3       164.0   West         93
43  2023-02-13        A   43.0  Product3       949.0   East         43
44  2023-02-14        A   96.0  Product3       830.0   East         96
45  2023-02-15        B   99.0  Product2       599.0   West         99
46  2023-02-16        B    6.0  Product1       938.0  South          6
47  2023-02-17        B   69.0  Product3       143.0   West         69
48  2023-02-18        C   65.0  Product3       182.0  North         65
49  2023-02-19        C   11.0  Product3       708.0  North         11

In [24]:
# How to do modification in the data of the column.

df.head(6)

df['Updated_Value'] = df['Value'].apply(lambda x: x*2)
df

Date Category  Value   Product  Sales_Data Region  Value_New  \
0   2023-01-01        A   28.0  Product1       754.0   East         28   
1   2023-01-02        B   39.0  Product3       110.0  North         39   
2   2023-01-03        C   32.0  Product2       398.0   East         32   
3   2023-01-04        B    8.0  Product1       522.0   East          8   
4   2023-01-05        B   26.0  Product3       869.0  North         26   
5   2023-01-06        B   54.0  Product3       192.0   West         54   
6   2023-01-07        A   16.0  Product1       936.0   East         16   
7   2023-01-08        C   89.0  Product1       488.0   West         89   
8   2023-01-09        C   37.0  Product3       772.0   West         37   
9   2023-01-10        A   22.0  Product2       834.0   West         22   
10  2023-01-11        B    7.0  Product1       842.0  North          7   
11  2023-01-12        B   60.0  Product2         NaN   West         60   
12  2023-01-13        A   70.0  Product3       628.0  South         70   
13  2023-01-14        A   69.0  Product1       423.0   East         69   
14  2023-01-15        A   47.0  Product2       893.0   West         47   
15  2023-01-16        C    NaN  Product1       895.0  North         51   
16  2023-01-17        C   93.0  Product2       511.0  South         93   
17  2023-01-18        C    NaN  Product1       108.0   West         51   
18  2023-01-19        A   31.0  Product2       578.0   West         31   
19  2023-01-20        A   59.0  Product1       736.0   East         59   
20  2023-01-21        C   82.0  Product3       606.0  South         82   
21  2023-01-22        C   37.0  Product2       992.0  South         37   
22  2023-01-23        B   62.0  Product3       942.0  North         62   
23  2023-01-24        C   92.0  Product2       342.0   West         92   
24  2023-01-25        A   24.0  Product2       458.0   East         24   
25  2023-01-26        C   95.0  Product1       584.0   West         95   
26  2023-01-27        C   71.0  Product2       619.0  North         71   
27  2023-01-28        C   56.0  Product2       224.0  North         56   
28  2023-01-29        B    NaN  Product3       617.0  North         51   
29  2023-01-30        C   51.0  Product2       737.0  South         51   
30  2023-01-31        B   50.0  Product3       735.0   West         50   
31  2023-02-01        A   17.0  Product2       189.0   West         17   
32  2023-02-02        B   63.0  Product3       338.0  South         63   
33  2023-02-03        C   27.0  Product3         NaN   East         27   
34  2023-02-04        C   70.0  Product3       669.0   West         70   
35  2023-02-05        B   60.0  Product2         NaN   West         60   
36  2023-02-06        C   36.0  Product3       177.0   East         36   
37  2023-02-07        C    2.0  Product1         NaN  North          2   
38  2023-02-08        C   94.0  Product1       408.0  South         94   
39  2023-02-09        A   62.0  Product1       155.0   West         62   
40  2023-02-10        B   15.0  Product1       578.0   East         15   
41  2023-02-11        C   97.0  Product1       256.0   East         97   
42  2023-02-12        A   93.0  Product3       164.0   West         93   
43  2023-02-13        A   43.0  Product3       949.0   East         43   
44  2023-02-14        A   96.0  Product3       830.0   East         96   
45  2023-02-15        B   99.0  Product2       599.0   West         99   
46  2023-02-16        B    6.0  Product1       938.0  South          6   
47  2023-02-17        B   69.0  Product3       143.0   West         69   
48  2023-02-18        C   65.0  Product3       182.0  North         65   
49  2023-02-19        C   11.0  Product3       708.0  North         11   

    Updated_Value  
0            56.0  
1            78.0  
2            64.0  
3            16.0  
4            52.0  
5           108.0  
6            32.0  
7           178.0  
8            74.0  
9            44.0  
10           14