# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation✅

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
## Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np

array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

array[:, 2] = 1
print("Modified array:")
print(array)

Original array:
[[14  2 20 19 11]
 [ 6  3 16 18 18]
 [15 20 10 18 18]
 [14  3 20 14  9]
 [18  4  9 10 16]]
Modified array:
[[14  2  1 19 11]
 [ 6  3  1 18 18]
 [15 20  1 18 18]
 [14  3  1 14  9]
 [18  4  1 10 16]]


In [ ]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

array = np.array([x for x  in range(1, 17)]).reshape(4, 4)

np.fill_diagonal(array, 0)
array

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [4]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

array = np.arange(1, 37).reshape((6, 6))
print(array)

array[2 : 5, 1 : 4]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [5]:
## Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[12  7 10  8 15]
 [ 8 15  7 20 16]
 [ 1 12 10  3  4]
 [11  3  3 11 14]
 [ 9 15 14 20 16]]
Border elements:
[12  7 10  8 15  9 15 14 20 16  8  1 11 16  4 14]


In [6]:
## Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2


Array 1:
[[ 5  9  7  9]
 [10 10  7  8]
 [ 1  7  8  3]]
Array 2:
[[ 4  9  6  7]
 [ 8 10  9  2]
 [ 7  3  7  5]]


In [7]:
## Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

array = np.arange(1, 17).reshape(4, 4)
print(array)

row_sum = np.sum(array, axis=1)
col_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(col_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


In [8]:
## Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

array = np.random.randint(1, 26, size=(5, 5))

mean=np.mean(array)
median=np.median(array)
std_dev=np.std(array)
var=np.var(array)

print(mean, median, std_dev, var)


13.2 12.0 6.554387843269576 42.96000000000001


In [9]:
## Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

array = np.arange(1, 10).reshape(3, 3)

mean = np.mean(array)
std_dev = np.std(array)

normalized_array = (array - mean) / std_dev

normalized_array


array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [10]:
## Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

array = np.random.randint(2, 56, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))

print(array)
print(row_array)

result = array + row_array
print(result)

[[36 45 42]
 [ 4  5  5]
 [52 35 44]]
[9 9 7]
[[45 54 49]
 [13 14 12]
 [61 44 51]]


In [15]:
## Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

array = np.random.randint(3, 48, size=(4, 4))
column_array=np.random.randint(1, 11, size=(4, ))

print(array)
print(column_array)

result=array - column_array[:, np.newaxis]
print(result)

[[ 6 20 36 28]
 [19  7 34 21]
 [41 37 42 21]
 [26  9 17 16]]
[4 1 1 6]
[[ 2 16 32 24]
 [18  6 33 20]
 [40 36 41 20]
 [20  3 11 10]]


In [20]:
## Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

matrix=np.random.randint(1, 20, size=(3, 3))
print("Original matrix:")
print(matrix)

determinant=np.linalg.det(matrix)
print("Determinant:", determinant)

inverse=np.linalg.inv(matrix)
print("Inverse :")
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Original matrix:
[[ 2  2  4]
 [ 3 11  3]
 [11  1  6]]
Determinant: -315.9999999999998
Inverse :
[[-0.19936709  0.02531646  0.12025316]
 [-0.04746835  0.10126582 -0.01898734]
 [ 0.37341772 -0.06329114 -0.05063291]]
Eigenvalues: [-2.87535598  7.817844   14.05751198]


In [21]:
## Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

arr1 = np.random.randint(1, 21, size=(2, 3))
arr2 = np.random.randint(1, 21, size=(3, 2))

result=np.dot(arr1, arr2)
print(result)

[[285 295]
 [309 334]]


In [24]:
## Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

array=np.arange(1, 10).reshape(3, 3)

arr1 = array.reshape(1, 9)
arr2 = array.reshape(9, 1)

print(arr2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [31]:
## Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

array=np.random.randint(1, 51, size=(5, 5))

flattened_array = array.flatten()

reshaped_array=flattened_array.reshape(5, 5)
reshaped_array

array([[23, 16, 11, 46,  9],
       [26, 26, 17, 46, 27],
       [38, 42, 48,  5, 29],
       [ 9, 49, 31, 25,  3],
       [48, 44, 18, 21, 23]], dtype=int32)

In [34]:
## Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

array=np.random.randint(1, 51, size=(5, 5))
print(array)

corners=array[[0, 0, -1, -1],[0, -1, 0, -1]]
print(corners)

[[24 33 27 48 34]
 [43 49 36 39 49]
 [13 39 26 34 27]
 [15 33 47 28 45]
 [32 12 19 45 16]]
[24 34 32 16]


In [35]:
## Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

array=np.random.randint(1, 51, size=(4, 4))

print(array)

array[array > 10] = 10
print(array)

[[44 40 10 39]
 [ 9 22 15 43]
 [28 35 50 17]
 [ 6 40 47 40]]
[[10 10 10 10]
 [ 9 10 10 10]
 [10 10 10 10]
 [ 6 10 10 10]]


In [39]:
## Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

sum = masked_array.sum()
print(sum)

Original array:
[[ 1 17 18 19]
 [15  8 13 11]
 [ 6 19 17  4]
 [18  6  7 12]]
Masked array:
[[1 -- -- --]
 [-- 8 -- --]
 [6 -- -- 4]
 [-- 6 7 --]]
32


In [43]:
## Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

import numpy.ma as ma

array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)

print(masked_array)

[[ 9  6  9]
 [ 8  9 11]
 [10 11  9]]
